{% set name = "ZODB" %}
{% set version = "5.5.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "a1fc0f925f5e9f0d43f6385ecd4aa653c8ee9f9b64dfedd54ab28f15c6b4c2a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  preserve_egg_dir: True
  entry_points:
    - fsdump=ZODB.FileStorage.fsdump:main
    - fsoids=ZODB.scripts.fsoids:main
    - fsrefs=ZODB.scripts.fsrefs:main
    - fstail=ZODB.scripts.fstail:Main
    - repozo=ZODB.scripts.repozo:main

  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - setuptools
    - persistent >=4.2.0
    - btrees >=4.2.0
    - zconfig
    - transaction >=2.0.3
    - six
    - zc.lockfile
    - zope.interface
    - zodbpickle >=0.6.0

test:
  imports:
    - ZODB
    - ZODB.FileStorage
    - ZODB.scripts
    - ZODB.scripts.tests
    - ZODB.tests

  commands:
    # - fsdump --help  # no support for --help
    # - fsoids --help  # no support for --help
    # - fsrefs --help  # no support for --help
    # - fstail --help  # no support for --help
    - repozo --help

about:
  home: http://www.zodb.org/
  license_file: LICENSE.txt
  license: ZPL 2.1
  license_family: OTHER
  summary: 'ZODB, a Python object-oriented database'
  dev_url: https://github.com/zopefoundation/ZODB
  doc_url: http://www.zodb.org/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
