{% set name = "ZODB" %}
{% set version = "5.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa40bbc05ecda1ec2435cd0c6dd02a13b7698460558a4604366f6a0a68401cd3

build:
  noarch: python
  entry_points:
    - fsdump=ZODB.FileStorage.fsdump:main
    - fsoids=ZODB.scripts.fsoids:main
    - fsrefs=ZODB.scripts.fsrefs:main
    - fstail=ZODB.scripts.fstail:Main
    - repozo=ZODB.scripts.repozo:main

  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - setuptools
    - persistent >=4.2.0
    - btrees >=4.2.0
    - zconfig
    - transaction >=2.0.3
    - six
    - zc.lockfile
    - zope.interface
    - zodbpickle >=0.6.0

test:
  imports:
    - ZODB
    - ZODB.FileStorage
    - ZODB.scripts
    - ZODB.scripts.tests
    - ZODB.tests

  commands:
    # - fsdump --help  # no support for --help
    # - fsoids --help  # no support for --help
    # - fsrefs --help  # no support for --help
    # - fstail --help  # no support for --help
    - repozo --help
    - pip check

  requires:
    - pip

about:
  home: http://www.zodb.org/
  license_file: LICENSE.txt
  license: ZPL-2.1
  license_family: OTHER
  summary: ZODB, a Python object-oriented database
  dev_url: https://github.com/zopefoundation/ZODB
  doc_url: http://www.zodb.org/en/latest/

extra:
  recipe-maintainers:
    - jan-janssen
