travis:
  secure:
    BINSTAR_TOKEN: Rq7W8xWij3hK14NcjRPwDOdn/LTpmiCLJOBpsCIwbgK6r45Dh2xWon4/ekiMSlLjbHRAg7cPLxG/OuXMXSLQbzQhRp6cEpp2ORQK1oPZhFRkVV4DC2wAx9zzqhyfySiMdhALGUTceFU4jZ8gwK/M5oXiq7FaaD2m7shL95u7+cbffgdtnu/aszJ2LvAFtdI/s+6+/643EaOGHduozcPSPmBkNGmqzCXnchq8I0bIjdjz3IQDBKHJiWSQCQaI+64PAuRK67UFHw1ssL3dvDsvv9s8tsmCnePWD0sXSdXwbZDpgH5UG5mrOUVD0yoo6XwhdXYNGuuEG/ClqLaLCdi8oDJ1BxA/GlorBT4pgivd3yj43bhk+pCqKeouL48IxskUjs0c7lo0MUIed/6EchSWcNqhlaUBEzyr25gTefIqf2tAJnFG01sDkN/JUK3y7ddkMY0kHxybII1AZYZh5c7UpV5jHp3FVwCwUYBoAfAnXYMTG7hdOvLtoNoWwkUYSnb4xpr775u7E+5H5v0qTBvlx5inzQ9Rap5xx8YHG1ndk+EQ2rXwd8uiSMX7O+PDS3oGMasjsDfdcKC52HJOI4W2aG99w6TImxNYAZptIBEKPyq+w5BrEo6ny2y3UF6vhdNQQ2VaHInLqCJZIvBmiGs2tGNyW7zLrJ/Y8RDOVwp2ZRQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
