travis:
  secure:
    BINSTAR_TOKEN: TzawcL2hGUE8SVD5QiNfN1A91scZDlaLEBnIrIYWl0NhH245VaDY5/937ZvZOpk1FBSgoqYziCsF9DYoSN4YoFqpS5sXUL+dUEx92njkHEzYAL0eKJmUU6n11SYaotlNEBnOIrTnIAOL6sR82T+OVdcjBAlR/VgbtAH5k0yeylguK/IzTTqu9zyDh0G7VP5/Ez2x3aXPqZjWUsq1Y5Y2qiI6GSQEDkl1Q9h76iOnkYaufXzPwwF97z3ArlR21kstVwAXQi8bAVmrhzapdLbLpWe64vMGaZK8jmRaGpsVtL0kxZd9xj8xAbiOZBZXVC/ekOceH/0i+aZN6Fwk1YmGb1Ls28qq10xQcoZy8SJYMHgyz9oJhK3JNWEx8Z9MueDcUG0S99omhW3fqGZer9oT/lDoBv5kf/YGyeNzxulNAwK3n4U1JclvWaFQvJcJNMdtsJhmYDZeDbdf3f66Fq1mRWpuJ8mJC7v8zw5IPTQs25tB8P15RTBo34IbIed3/YNp/H6gb6TzIgMFPt4fBno+desDbH7jX0bPD/WcbmNsMt7EKT7CjLK9GehtOUcvjWYETQcO4dOPqhPPErWz9PYuoIRGoNyrG/wvJAsJePbjzzn3Gh95PpR4XLiVgxi/AZY3sWpQJ2YQUIZdox0nMrdjww5Sahp7KjvITc1ASp4T5so=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
